[package]
name = "decanmovie-bridge"
version = "0.1.0"
edition = "2024"

[lib]
name = "decanmovie_bridge"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
serde_json = "1.0"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros", "time"] }
moviebox-tui = { path = "../MovieBox-Tui" }
